# kubectl apply -f duban-salas-35-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: duban-salas-35-secret
  namespace: duban-salas-35-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXJvdWdoLWRyZWFtLWE1amd2MDF1LXBvb2xlci51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9zcWw/c3NsbW9kZT1yZXF1aXJl
  DATABASE_USERNAME: ZGJfb3duZXI=
  DATABASE_PASSWORD: Q1R0cVhpNkcyTkZ4
  RAPIDAPI_APIKEY: MzA1NGRjYTI5NG1zaDMxMWZjYzE2ODkzY2U3NHAxN2VmMjRqc25jYmQ4ZWFkNmVkNzY=
  RAPIDAPI_YT_URL: aHR0cHM6Ly95dC1hcGkucC5yYXBpZGFwaS5jb20=
  RAPIDAPI_YT_HOST: eXQtYXBpLnAucmFwaWRhcGkuY29t
  RAPIDAPI_SPOTIFY_URL: aHR0cHM6Ly9zcG90aWZ5LXdlYi1hcGkzLnAucmFwaWRhcGkuY29t
  RAPIDAPI_SPOTIFY_HOST: c3BvdGlmeS13ZWItYXBpMy5wLnJhcGlkYXBpLmNvbQ==

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode