# kubectl apply -f duban-salas-35-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: duban-salas-35-secret
  namespace: duban-salas-35-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  DATABASE_URL:    # en Base64
  DATABASE_USERNAME:    # en Base64
  DATABASE_PASSWORD:  # en Base64
  RAPIDAPI_YT_URL:   # en Base64
  RAPIDAPI_YT_HOST:  # en Base64
  RAPIDAPI_APIKEY:    # en Base64
  RAPIDAPI_SPOTIFY_URL:    # en Base64
  RAPIDAPI_SPOTIFY_HOST:    # en Base64
  RAPIDAPI_APIKEY:   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode